version: '3'
networks:
  web:
    external: true
services:
  srtdash:
    build: ./app
    image: mikeryan56/quart-dashboard:latest
    restart: always
    ports:
    - "5000"
    volumes:
    - .:/code

    # if using jwilder/nginx-proxy
    # environment:
    # - VIRTUAL_HOST=srtdash.devsetgo.com
    # - LETSENCRYPT_HOST=srtdash.devsetgo.com

    #if using traefik
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.quart-dashboard.rule=Host(`quart-dashboard.devsetgo.com`)"
    - "traefik.http.routers.quart-dashboard.entrypoints=websecure"
    - "traefik.http.routers.quart-dashboard.tls.certresolver=mytlschallenge"
    networks:
      - web
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
#      restart_policy:
#        condition: always
